// Generated from templates/**/*.md by scripts/sync-templates.mjs.
export const bundledTemplates = {
  "en": {
    "meeting": "<!-- notegen-template\n{\n  \"fields\": [\n    {\n      \"id\": \"topic\",\n      \"label\": \"Meeting topic\",\n      \"type\": \"text\",\n      \"required\": true\n    },\n    {\n      \"id\": \"people\",\n      \"label\": \"Participants\",\n      \"type\": \"text\"\n    }\n  ]\n}\n-->\n# {{title}}\n\nDate: {{date}} {{time}}\nTopic: {{field.topic}}\nParticipants: {{field.people}}\n\n## Agenda\n\n- \n\n## Discussion\n\n{{selection}}\n\n## Decisions\n\n- \n\n## Action items\n\n- [ ] Owner — task — due date\n",
    "daily": "<!-- notegen-template\n{\n  \"fields\": [\n    {\n      \"id\": \"topic\",\n      \"label\": \"Daily focus\",\n      \"type\": \"text\",\n      \"required\": true\n    }\n  ]\n}\n-->\n# {{title}}\n\nDate: {{date}}\nFocus: {{field.topic}}\n\n## Completed\n\n- \n\n## In progress\n\n- \n\n## Blockers\n\n- \n\n## Tomorrow\n\n- [ ] \n\n## Context\n\n{{selection}}\n",
    "reading": "<!-- notegen-template\n{\n  \"fields\": [\n    {\n      \"id\": \"topic\",\n      \"label\": \"Book title\",\n      \"type\": \"text\",\n      \"required\": true\n    },\n    {\n      \"id\": \"author\",\n      \"label\": \"Author\",\n      \"type\": \"text\"\n    }\n  ]\n}\n-->\n# {{title}}\n\nBook: {{field.topic}}\nAuthor: {{field.author}}\nRecorded: {{datetime}}\n\n## Key ideas\n\n- \n\n## Quotes\n\n{{selection}}\n\n## My thoughts\n\n\n## Next actions\n\n- [ ]\n"
  },
  "zh-CN": {
    "meeting": "<!-- notegen-template\n{\n  \"fields\": [\n    {\n      \"id\": \"topic\",\n      \"label\": \"会议主题\",\n      \"type\": \"text\",\n      \"required\": true\n    },\n    {\n      \"id\": \"people\",\n      \"label\": \"参会人员\",\n      \"type\": \"text\"\n    }\n  ]\n}\n-->\n# {{title}}\n\n日期：{{date}} {{time}}\n主题：{{field.topic}}\n参会人员：{{field.people}}\n\n## 议程\n\n- \n\n## 讨论记录\n\n{{selection}}\n\n## 决议\n\n- \n\n## 待办事项\n\n- [ ] 负责人 — 任务 — 截止日期\n",
    "daily": "<!-- notegen-template\n{\n  \"fields\": [\n    {\n      \"id\": \"topic\",\n      \"label\": \"今日重点\",\n      \"type\": \"text\",\n      \"required\": true\n    }\n  ]\n}\n-->\n# {{title}}\n\n日期：{{date}}\n重点：{{field.topic}}\n\n## 今日完成\n\n- \n\n## 进行中\n\n- \n\n## 遇到的问题\n\n- \n\n## 明日计划\n\n- [ ] \n\n## 补充记录\n\n{{selection}}\n",
    "reading": "<!-- notegen-template\n{\n  \"fields\": [\n    {\n      \"id\": \"topic\",\n      \"label\": \"书名\",\n      \"type\": \"text\",\n      \"required\": true\n    },\n    {\n      \"id\": \"author\",\n      \"label\": \"作者\",\n      \"type\": \"text\"\n    }\n  ]\n}\n-->\n# {{title}}\n\n书名：{{field.topic}}\n作者：{{field.author}}\n记录时间：{{datetime}}\n\n## 核心观点\n\n- \n\n## 摘录\n\n{{selection}}\n\n## 我的思考\n\n\n## 行动计划\n\n- [ ]\n"
  }
} as const
